# Generated by Django 4.1.3 on 2022-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('EtatVaccin', models.BooleanField(blank=True, null=True)),
                ('EtatAdopt', models.BooleanField(blank=True, null=True)),
                ('EtatDressage', models.BooleanField(blank=True, null=True)),
                ('Added', models.DateField(blank=True, null=True)),
                ('EtatCastre', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.TextField(blank=True, null=True)),
                ('Role', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
